name: TeamCity DSL Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Start TeamCity with docker compose
        run: docker compose up -d tc-server tc-agent

      - name: Wait for TeamCity HTTP to load
        run: |
          echo "Waiting for http://localhost:8111 ..."
          for i in $(seq 1 120); do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8111 || true)
            if [ "$code" = "401" ]; then
              echo "Server is ready, HTTP $code"
              break
            fi
            sleep 2
          done

      - name: Bootstrap TeamCity admin
        run: |
          chmod +x scripts/bootstrap-admin.sh
          ./scripts/bootstrap-admin.sh

      - name: Build tests
        run: mvn -q -DskipTests package

      - name: Run tests
        env:
          VCS_PAT: ${{ secrets.VCS_PAT }}
          VCS_USERNAME: ${{ secrets.VCS_USERNAME }}
        run: mvn -q test

      - name: Dump logs on failure
        if: failure()
        run: |
          echo "===== tc-server logs ====="
          docker compose logs tc-server || true
          echo "===== tc-agent logs ====="
          docker compose logs tc-agent || true

      - name: Teardown
        if: always()
        run: docker compose down -v
